In [1]:
import pandas as pd
import numpy as np
import re
import os
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer

In [2]:
# import dataset in the csv format only
class AncientGreece():
    # check whether the file exists
    def file_exists(self, file_path):
        return os.path.isfile(file_path)
        
    def load_dataset(self, file_path):
        # Load the dataset if it exists and also if it is a valid csv
        if not file_path.endswith ("csv"):
            raise ValueError("SORRY! You Provided an Unsupported File Format.")

            # return FileNotFoundError
        if not self.file_exists(file_path): # logic function to check if the file exists
            raise FileNotFoundError(f"OOOOPS! Your file '{file_path}' does not exist.")

        try :
            # reading a file with encoding handling
            return pd.read_csv(file_path, encoding = "utf-8")
        except UnicodeError:
            # try file encoding ISO-8859-1
            return pd.read_csv(file_path, encoding = "ISO-8859-1")
        except Exception as e:
            raise ValueError(f"Failed to load dataset {e}")
                
greece= AncientGreece()
file_path = r"C:\Kimani\Simba\CSVs\wikipedia_data_Ancient Greece(in).csv"

try:
    df = greece.load_dataset(file_path)
    print(df.head())

except Exception as e:
    print (e) # prints an error message if anything goes wrong

# this function only reads the csv filetype and otherwise will raise a ValueError
try:
    df = greece.load_dataset(file_path)
    print(df.head())

except Exception as e:
    print (e) # prints an error message if anything goes wrong

# this function only reads the csv filetype and otherwise will raise a ValueError

                       title  \
0             Ancient Greece
1              Ancient Greek
2   Ancient Greek philosophy
3     Ancient Greek religion
4  Theatre of ancient Greece

                                                 url  \
0       https://en.wikipedia.org/wiki/Ancient_Greece
1        https://en.wikipedia.org/wiki/Ancient_Greek
2  https://en.wikipedia.org/wiki/Ancient_Greek_ph...
3  https://en.wikipedia.org/wiki/Ancient_Greek_re...
4  https://en.wikipedia.org/wiki/Theatre_of_ancie...

                                             summary  \
0  Ancient Greece(Ancient Greek:á¼Î»Î»Î¬Ï,roman...
1  Ancient Greek(á¼Î»Î»Î·Î½á¿ÎºÎ®,HellÄniká¸;...
2  Ancient Greek philosophyarose in the 6th centu...
3  Religious practices in ancient Greeceencompass...
4  Atheatricalculture flourished inancient Greece...

                                             content  \
0                                                NaN
1                                                NaN
2  ## introduction\nAncient Greek philosophyarose...
3                                                NaN
4  ## introduction\nAtheatricalculture flourished...

                                              images  \
0  https://upload.wikimedia.org/wikipedia/en/thum...
1  https://upload.wikimedia.org/wikipedia/en/thum...
2  https://upload.wikimedia.org/wikipedia/commons...
3  https://upload.wikimedia.org/wikipedia/en/thum...
4  https://upload.wikimedia.org/wikipedia/en/thum...

                                          references  \
0  ^This roughly 15-year-long unification, underP...
1  ^Mycenaean Greekis imprecisely attested and so...
2  ^Alfred North Whitehead (1929),Process and Rea...
3  ^abBarbette Stanley Spaeth(2013).The Cambridge...
4  ^"Merriam-Webster definition of tragedy".Archi...

                                          categories Unnamed: 7 Unnamed: 8  \
0                                     Ancient Greece        NaN        NaN
1  Ancient Greek,Ancient Greece,Languages atteste...        NaN        NaN
2  Ancient Greek philosophy,Ancient philosophy by...        NaN        NaN
3                             Ancient Greek religion        NaN        NaN
4  Ancient Greek theatre,Ancient Greek dramatists...        NaN        NaN

  Unnamed: 9  ... Unnamed: 49 Unnamed: 50 Unnamed: 51 Unnamed: 52 Unnamed: 53  \
0        NaN  ...         NaN         NaN         NaN         NaN         NaN
1        NaN  ...         NaN         NaN         NaN         NaN         NaN
2        NaN  ...         NaN         NaN         NaN         NaN         NaN
3        NaN  ...         NaN         NaN         NaN         NaN         NaN
4        NaN  ...         NaN         NaN         NaN         NaN         NaN

  Unnamed: 54 Unnamed: 55 Unnamed: 56 Unnamed: 57 Unnamed: 58
0         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN
2         NaN         NaN         NaN         NaN         NaN
3         NaN         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN         NaN

[5 rows x 59 columns]
                       title  \
0             Ancient Greece
1              Ancient Greek
2   Ancient Greek philosophy
3     Ancient Greek religion
4  Theatre of ancient Greece

                                                 url  \
0       https://en.wikipedia.org/wiki/Ancient_Greece
1        https://en.wikipedia.org/wiki/Ancient_Greek
2  https://en.wikipedia.org/wiki/Ancient_Greek_ph...
3  https://en.wikipedia.org/wiki/Ancient_Greek_re...
4  https://en.wikipedia.org/wiki/Theatre_of_ancie...

                                             summary  \
0  Ancient Greece(Ancient Greek:á¼Î»Î»Î¬Ï,roman...
1  Ancient Greek(á¼Î»Î»Î·Î½á¿ÎºÎ®,HellÄniká¸;...
2  Ancient Greek philosophyarose in the 6th centu...
3  Religious practices in ancient Greeceencompass...
4  Atheatricalculture flourished inancient Greece...

                                             content  \
0                                                NaN
1                                                NaN
2  ## introduction\nAncient Greek philosophyarose...
3                                                NaN
4  ## introduction\nAtheatricalculture flourished...

                                              images  \
0  https://upload.wikimedia.org/wikipedia/en/thum...
1  https://upload.wikimedia.org/wikipedia/en/thum...
2  https://upload.wikimedia.org/wikipedia/commons...
3  https://upload.wikimedia.org/wikipedia/en/thum...
4  https://upload.wikimedia.org/wikipedia/en/thum...

                                          references  \
0  ^This roughly 15-year-long unification, underP...
1  ^Mycenaean Greekis imprecisely attested and so...
2  ^Alfred North Whitehead (1929),Process and Rea...
3  ^abBarbette Stanley Spaeth(2013).The Cambridge...
4  ^"Merriam-Webster definition of tragedy".Archi...

                                          categories Unnamed: 7 Unnamed: 8  \
0                                     Ancient Greece        NaN        NaN
1  Ancient Greek,Ancient Greece,Languages atteste...        NaN        NaN
2  Ancient Greek philosophy,Ancient philosophy by...        NaN        NaN
3                             Ancient Greek religion        NaN        NaN
4  Ancient Greek theatre,Ancient Greek dramatists...        NaN        NaN

  Unnamed: 9  ... Unnamed: 49 Unnamed: 50 Unnamed: 51 Unnamed: 52 Unnamed: 53  \
0        NaN  ...         NaN         NaN         NaN         NaN         NaN
1        NaN  ...         NaN         NaN         NaN         NaN         NaN
2        NaN  ...         NaN         NaN         NaN         NaN         NaN
3        NaN  ...         NaN         NaN         NaN         NaN         NaN
4        NaN  ...         NaN         NaN         NaN         NaN         NaN

  Unnamed: 54 Unnamed: 55 Unnamed: 56 Unnamed: 57 Unnamed: 58
0         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN
2         NaN         NaN         NaN         NaN         NaN
3         NaN         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN         NaN

[5 rows x 59 columns]

In [3]:
print("\n **Dataset Overview**")
df.info()

print("\n **Data type in column title**")
print(df['title'].dtype)

# to find different datatypes in all the columns
print("\n **Different Datatypes in all columns**")
type_counts = df.apply(type).nunique()
print(type_counts)
print("\n **Datatype Distribution in each column**")
# Datatypes distribution in each colummn
for col in df.columns:
    print (f"Column: {col}")
    print (df[col].apply(lambda x: type(x)).value_counts(), "\n")

 **Dataset Overview**
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2725 entries, 0 to 2724
Data columns (total 59 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        2720 non-null   object
 1   url          2060 non-null   object
 2   summary      1391 non-null   object
 3   content      995 non-null    object
 4   images       927 non-null    object
 5   references   797 non-null    object
 6   categories   744 non-null    object
 7   Unnamed: 7   188 non-null    object
 8   Unnamed: 8   153 non-null    object
 9   Unnamed: 9   111 non-null    object
 10  Unnamed: 10  91 non-null     object
 11  Unnamed: 11  69 non-null     object
 12  Unnamed: 12  56 non-null     object
 13  Unnamed: 13  48 non-null     object
 14  Unnamed: 14  38 non-null     object
 15  Unnamed: 15  30 non-null     object
 16  Unnamed: 16  27 non-null     object
 17  Unnamed: 17  21 non-null     object
 18  Unnamed: 18  18 non-null     object
 19  Unnamed: 19  13 non-null     object
 20  Unnamed: 20  12 non-null     object
 21  Unnamed: 21  10 non-null     object
 22  Unnamed: 22  8 non-null      object
 23  Unnamed: 23  6 non-null      object
 24  Unnamed: 24  6 non-null      object
 25  Unnamed: 25  4 non-null      object
 26  Unnamed: 26  4 non-null      object
 27  Unnamed: 27  4 non-null      object
 28  Unnamed: 28  4 non-null      object
 29  Unnamed: 29  4 non-null      object
 30  Unnamed: 30  4 non-null      object
 31  Unnamed: 31  3 non-null      object
 32  Unnamed: 32  3 non-null      object
 33  Unnamed: 33  3 non-null      object
 34  Unnamed: 34  2 non-null      object
 35  Unnamed: 35  2 non-null      object
 36  Unnamed: 36  2 non-null      object
 37  Unnamed: 37  2 non-null      object
 38  Unnamed: 38  2 non-null      object
 39  Unnamed: 39  2 non-null      object
 40  Unnamed: 40  2 non-null      object
 41  Unnamed: 41  2 non-null      object
 42  Unnamed: 42  2 non-null      object
 43  Unnamed: 43  2 non-null      object
 44  Unnamed: 44  2 non-null      object
 45  Unnamed: 45  2 non-null      object
 46  Unnamed: 46  2 non-null      object
 47  Unnamed: 47  2 non-null      object
 48  Unnamed: 48  2 non-null      object
 49  Unnamed: 49  2 non-null      object
 50  Unnamed: 50  2 non-null      object
 51  Unnamed: 51  2 non-null      object
 52  Unnamed: 52  2 non-null      object
 53  Unnamed: 53  2 non-null      object
 54  Unnamed: 54  2 non-null      object
 55  Unnamed: 55  2 non-null      object
 56  Unnamed: 56  2 non-null      object
 57  Unnamed: 57  2 non-null      float64
 58  Unnamed: 58  2 non-null      object
dtypes: float64(1), object(58)
memory usage: 1.2+ MB

 **Data type in column title**
object

 **Different Datatypes in all columns**
1

 **Datatype Distribution in each column**
Column: title
title
<class 'str'>      2720
<class 'float'>       5
Name: count, dtype: int64

Column: url
url
<class 'str'>      2060
<class 'float'>     665
Name: count, dtype: int64

Column: summary
summary
<class 'str'>      1391
<class 'float'>    1334
Name: count, dtype: int64

Column: content
content
<class 'float'>    1730
<class 'str'>       995
Name: count, dtype: int64

Column: images
images
<class 'float'>    1798
<class 'str'>       927
Name: count, dtype: int64

Column: references
references
<class 'float'>    1928
<class 'str'>       797
Name: count, dtype: int64

Column: categories
categories
<class 'float'>    1981
<class 'str'>       744
Name: count, dtype: int64

Column: Unnamed: 7
Unnamed: 7
<class 'float'>    2537
<class 'str'>       188
Name: count, dtype: int64

Column: Unnamed: 8
Unnamed: 8
<class 'float'>    2572
<class 'str'>       153
Name: count, dtype: int64

Column: Unnamed: 9
Unnamed: 9
<class 'float'>    2614
<class 'str'>       111
Name: count, dtype: int64

Column: Unnamed: 10
Unnamed: 10
<class 'float'>    2634
<class 'str'>        91
Name: count, dtype: int64

Column: Unnamed: 11
Unnamed: 11
<class 'float'>    2656
<class 'str'>        69
Name: count, dtype: int64

Column: Unnamed: 12
Unnamed: 12
<class 'float'>    2669
<class 'str'>        56
Name: count, dtype: int64

Column: Unnamed: 13
Unnamed: 13
<class 'float'>    2677
<class 'str'>        48
Name: count, dtype: int64

Column: Unnamed: 14
Unnamed: 14
<class 'float'>    2687
<class 'str'>        38
Name: count, dtype: int64

Column: Unnamed: 15
Unnamed: 15
<class 'float'>    2695
<class 'str'>        30
Name: count, dtype: int64

Column: Unnamed: 16
Unnamed: 16
<class 'float'>    2698
<class 'str'>        27
Name: count, dtype: int64

Column: Unnamed: 17
Unnamed: 17
<class 'float'>    2704
<class 'str'>        21
Name: count, dtype: int64

Column: Unnamed: 18
Unnamed: 18
<class 'float'>    2707
<class 'str'>        18
Name: count, dtype: int64

Column: Unnamed: 19
Unnamed: 19
<class 'float'>    2712
<class 'str'>        13
Name: count, dtype: int64

Column: Unnamed: 20
Unnamed: 20
<class 'float'>    2713
<class 'str'>        12
Name: count, dtype: int64

Column: Unnamed: 21
Unnamed: 21
<class 'float'>    2715
<class 'str'>        10
Name: count, dtype: int64

Column: Unnamed: 22
Unnamed: 22
<class 'float'>    2717
<class 'str'>         8
Name: count, dtype: int64

Column: Unnamed: 23
Unnamed: 23
<class 'float'>    2719
<class 'str'>         6
Name: count, dtype: int64

Column: Unnamed: 24
Unnamed: 24
<class 'float'>    2719
<class 'str'>         6
Name: count, dtype: int64

Column: Unnamed: 25
Unnamed: 25
<class 'float'>    2721
<class 'str'>         4
Name: count, dtype: int64

Column: Unnamed: 26
Unnamed: 26
<class 'float'>    2721
<class 'str'>         4
Name: count, dtype: int64

Column: Unnamed: 27
Unnamed: 27
<class 'float'>    2721
<class 'str'>         4
Name: count, dtype: int64

Column: Unnamed: 28
Unnamed: 28
<class 'float'>    2721
<class 'str'>         4
Name: count, dtype: int64

Column: Unnamed: 29
Unnamed: 29
<class 'float'>    2721
<class 'str'>         4
Name: count, dtype: int64

Column: Unnamed: 30
Unnamed: 30
<class 'float'>    2721
<class 'str'>         4
Name: count, dtype: int64

Column: Unnamed: 31
Unnamed: 31
<class 'float'>    2722
<class 'str'>         3
Name: count, dtype: int64

Column: Unnamed: 32
Unnamed: 32
<class 'float'>    2722
<class 'str'>         3
Name: count, dtype: int64

Column: Unnamed: 33
Unnamed: 33
<class 'float'>    2722
<class 'str'>         3
Name: count, dtype: int64

Column: Unnamed: 34
Unnamed: 34
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 35
Unnamed: 35
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 36
Unnamed: 36
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 37
Unnamed: 37
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 38
Unnamed: 38
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 39
Unnamed: 39
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 40
Unnamed: 40
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 41
Unnamed: 41
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 42
Unnamed: 42
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 43
Unnamed: 43
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 44
Unnamed: 44
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 45
Unnamed: 45
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 46
Unnamed: 46
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 47
Unnamed: 47
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 48
Unnamed: 48
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 49
Unnamed: 49
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 50
Unnamed: 50
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 51
Unnamed: 51
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 52
Unnamed: 52
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 53
Unnamed: 53
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 54
Unnamed: 54
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 55
Unnamed: 55
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 56
Unnamed: 56
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

Column: Unnamed: 57
Unnamed: 57
<class 'float'>    2725
Name: count, dtype: int64

Column: Unnamed: 58
Unnamed: 58
<class 'float'>    2723
<class 'str'>         2
Name: count, dtype: int64

In [4]:
def detect_issues(df):
    # checks if the dataset has some common issues and report them
       print("\n **Dataset Overview**")
       print(df.info())
    
       print("\n **Missing Values")
       print(df.isnull().sum())
    
       print("\n **Duplicate Rows**")
       print(f"The total number of duplicates is:{df.duplicated().sum()}")
    
       print("\n **Inconsistent Datatypes**")
       print(df.apply(type).head())
    
detect_issues(df)

 **Dataset Overview**
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2725 entries, 0 to 2724
Data columns (total 59 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        2720 non-null   object
 1   url          2060 non-null   object
 2   summary      1391 non-null   object
 3   content      995 non-null    object
 4   images       927 non-null    object
 5   references   797 non-null    object
 6   categories   744 non-null    object
 7   Unnamed: 7   188 non-null    object
 8   Unnamed: 8   153 non-null    object
 9   Unnamed: 9   111 non-null    object
 10  Unnamed: 10  91 non-null     object
 11  Unnamed: 11  69 non-null     object
 12  Unnamed: 12  56 non-null     object
 13  Unnamed: 13  48 non-null     object
 14  Unnamed: 14  38 non-null     object
 15  Unnamed: 15  30 non-null     object
 16  Unnamed: 16  27 non-null     object
 17  Unnamed: 17  21 non-null     object
 18  Unnamed: 18  18 non-null     object
 19  Unnamed: 19  13 non-null     object
 20  Unnamed: 20  12 non-null     object
 21  Unnamed: 21  10 non-null     object
 22  Unnamed: 22  8 non-null      object
 23  Unnamed: 23  6 non-null      object
 24  Unnamed: 24  6 non-null      object
 25  Unnamed: 25  4 non-null      object
 26  Unnamed: 26  4 non-null      object
 27  Unnamed: 27  4 non-null      object
 28  Unnamed: 28  4 non-null      object
 29  Unnamed: 29  4 non-null      object
 30  Unnamed: 30  4 non-null      object
 31  Unnamed: 31  3 non-null      object
 32  Unnamed: 32  3 non-null      object
 33  Unnamed: 33  3 non-null      object
 34  Unnamed: 34  2 non-null      object
 35  Unnamed: 35  2 non-null      object
 36  Unnamed: 36  2 non-null      object
 37  Unnamed: 37  2 non-null      object
 38  Unnamed: 38  2 non-null      object
 39  Unnamed: 39  2 non-null      object
 40  Unnamed: 40  2 non-null      object
 41  Unnamed: 41  2 non-null      object
 42  Unnamed: 42  2 non-null      object
 43  Unnamed: 43  2 non-null      object
 44  Unnamed: 44  2 non-null      object
 45  Unnamed: 45  2 non-null      object
 46  Unnamed: 46  2 non-null      object
 47  Unnamed: 47  2 non-null      object
 48  Unnamed: 48  2 non-null      object
 49  Unnamed: 49  2 non-null      object
 50  Unnamed: 50  2 non-null      object
 51  Unnamed: 51  2 non-null      object
 52  Unnamed: 52  2 non-null      object
 53  Unnamed: 53  2 non-null      object
 54  Unnamed: 54  2 non-null      object
 55  Unnamed: 55  2 non-null      object
 56  Unnamed: 56  2 non-null      object
 57  Unnamed: 57  2 non-null      float64
 58  Unnamed: 58  2 non-null      object
dtypes: float64(1), object(58)
memory usage: 1.2+ MB
None

 **Missing Values
title             5
url             665
summary        1334
content        1730
images         1798
references     1928
categories     1981
Unnamed: 7     2537
Unnamed: 8     2572
Unnamed: 9     2614
Unnamed: 10    2634
Unnamed: 11    2656
Unnamed: 12    2669
Unnamed: 13    2677
Unnamed: 14    2687
Unnamed: 15    2695
Unnamed: 16    2698
Unnamed: 17    2704
Unnamed: 18    2707
Unnamed: 19    2712
Unnamed: 20    2713
Unnamed: 21    2715
Unnamed: 22    2717
Unnamed: 23    2719
Unnamed: 24    2719
Unnamed: 25    2721
Unnamed: 26    2721
Unnamed: 27    2721
Unnamed: 28    2721
Unnamed: 29    2721
Unnamed: 30    2721
Unnamed: 31    2722
Unnamed: 32    2722
Unnamed: 33    2722
Unnamed: 34    2723
Unnamed: 35    2723
Unnamed: 36    2723
Unnamed: 37    2723
Unnamed: 38    2723
Unnamed: 39    2723
Unnamed: 40    2723
Unnamed: 41    2723
Unnamed: 42    2723
Unnamed: 43    2723
Unnamed: 44    2723
Unnamed: 45    2723
Unnamed: 46    2723
Unnamed: 47    2723
Unnamed: 48    2723
Unnamed: 49    2723
Unnamed: 50    2723
Unnamed: 51    2723
Unnamed: 52    2723
Unnamed: 53    2723
Unnamed: 54    2723
Unnamed: 55    2723
Unnamed: 56    2723
Unnamed: 57    2723
Unnamed: 58    2723
dtype: int64

 **Duplicate Rows**
The total number of duplicates is:132

 **Inconsistent Datatypes**
title      <class 'pandas.core.series.Series'>
url        <class 'pandas.core.series.Series'>
summary    <class 'pandas.core.series.Series'>
content    <class 'pandas.core.series.Series'>
images     <class 'pandas.core.series.Series'>
dtype: object

In [5]:
missing_values = df.isnull()
summary_percentage = missing_values['summary'].value_counts() / df['summary'].size 
content_percentage = missing_values['content'].value_counts() / df['summary'].size 

print(content_percentage)
print(summary_percentage)

content
True     0.634862
False    0.365138
Name: count, dtype: float64
summary
False    0.510459
True     0.489541
Name: count, dtype: float64

In [6]:
# check if the df is a dataframe
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [7]:
#removing the duplicates
df = df.drop_duplicates()
# check if the duplicates are gone
print("number of duplicate rows: ", df.duplicated())

number of duplicate rows:  0       False
1       False
2       False
3       False
4       False
        ...
2719    False
2720    False
2721    False
2723    False
2724    False
Length: 2593, dtype: bool

In [8]:
# Removing special characters
df["content"] = df["content"].str.replace(r"[^\w\s]", "", regex=True).str.replace("\n", "", regex=True)
df["summary"] = df["summary"].str.replace(r"[^\w\s]", "", regex=True).str.replace("\n", "", regex=True)
df["references"] = df["references"].str.replace(r"[^\w\s]", "", regex=True).str.replace("\n", "", regex=True)
df["categories"] = df["categories"].str.replace(r"[^\w\s]", "", regex=True).str.replace("\n", "", regex=True)
df["title"] = df["title"].str.replace(r"[^\w\s]", "", regex=True)

df.head()

,title,url,summary,content,images,references,categories,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58
0,Ancient Greece,https://en.wikipedia.org/wiki/Ancient_Greece,Ancient GreeceAncient Greeká¼ÎÎÎÏromanizedHell...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,This roughly 15yearlong unification underPhili...,Ancient Greece,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ancient Greek,https://en.wikipedia.org/wiki/Ancient_Greek,Ancient Greeká¼ÎÎÎÎ½áÎºÎHellÄnikáhellÉËnikÉÌË1...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,Mycenaean Greekis imprecisely attested and som...,Ancient GreekAncient GreeceLanguages attested ...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ancient Greek philosophy,https://en.wikipedia.org/wiki/Ancient_Greek_ph...,Ancient Greek philosophyarose in the 6th centu...,introductionAncient Greek philosophyarose in ...,https://upload.wikimedia.org/wikipedia/commons...,Alfred North Whitehead 1929Process and Reality...,Ancient Greek philosophyAncient philosophy by ...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ancient Greek religion,https://en.wikipedia.org/wiki/Ancient_Greek_re...,Religious practices in ancient Greeceencompass...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,abBarbette Stanley Spaeth2013The Cambridge com...,Ancient Greek religion,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Theatre of ancient Greece,https://en.wikipedia.org/wiki/Theatre_of_ancie...,Atheatricalculture flourished inancient Greece...,introductionAtheatricalculture flourished ina...,https://upload.wikimedia.org/wikipedia/en/thum...,MerriamWebster definition of tragedyArchivedfr...,Ancient Greek theatreAncient Greek dramatists ...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
missing_valuesdf1 = df.isnull()
for column in missing_valuesdf1.columns.values.tolist():
    print (missing_valuesdf1[column].value_counts())
    print("")

title
False    2591
True        2
Name: count, dtype: int64

url
False    1957
True      636
Name: count, dtype: int64

summary
False    1306
True     1287
Name: count, dtype: int64

content
True     1661
False     932
Name: count, dtype: int64

images
True     1732
False     861
Name: count, dtype: int64

references
True     1858
False     735
Name: count, dtype: int64

categories
True     1906
False     687
Name: count, dtype: int64

Unnamed: 7
True     2416
False     177
Name: count, dtype: int64

Unnamed: 8
True     2448
False     145
Name: count, dtype: int64

Unnamed: 9
True     2488
False     105
Name: count, dtype: int64

Unnamed: 10
True     2508
False      85
Name: count, dtype: int64

Unnamed: 11
True     2530
False      63
Name: count, dtype: int64

Unnamed: 12
True     2542
False      51
Name: count, dtype: int64

Unnamed: 13
True     2550
False      43
Name: count, dtype: int64

Unnamed: 14
True     2559
False      34
Name: count, dtype: int64

Unnamed: 15
True     2567
False      26
Name: count, dtype: int64

Unnamed: 16
True     2570
False      23
Name: count, dtype: int64

Unnamed: 17
True     2576
False      17
Name: count, dtype: int64

Unnamed: 18
True     2578
False      15
Name: count, dtype: int64

Unnamed: 19
True     2582
False      11
Name: count, dtype: int64

Unnamed: 20
True     2583
False      10
Name: count, dtype: int64

Unnamed: 21
True     2585
False       8
Name: count, dtype: int64

Unnamed: 22
True     2587
False       6
Name: count, dtype: int64

Unnamed: 23
True     2588
False       5
Name: count, dtype: int64

Unnamed: 24
True     2588
False       5
Name: count, dtype: int64

Unnamed: 25
True     2590
False       3
Name: count, dtype: int64

Unnamed: 26
True     2590
False       3
Name: count, dtype: int64

Unnamed: 27
True     2590
False       3
Name: count, dtype: int64

Unnamed: 28
True     2590
False       3
Name: count, dtype: int64

Unnamed: 29
True     2590
False       3
Name: count, dtype: int64

Unnamed: 30
True     2590
False       3
Name: count, dtype: int64

Unnamed: 31
True     2591
False       2
Name: count, dtype: int64

Unnamed: 32
True     2591
False       2
Name: count, dtype: int64

Unnamed: 33
True     2591
False       2
Name: count, dtype: int64

Unnamed: 34
True     2592
False       1
Name: count, dtype: int64

Unnamed: 35
True     2592
False       1
Name: count, dtype: int64

Unnamed: 36
True     2592
False       1
Name: count, dtype: int64

Unnamed: 37
True     2592
False       1
Name: count, dtype: int64

Unnamed: 38
True     2592
False       1
Name: count, dtype: int64

Unnamed: 39
True     2592
False       1
Name: count, dtype: int64

Unnamed: 40
True     2592
False       1
Name: count, dtype: int64

Unnamed: 41
True     2592
False       1
Name: count, dtype: int64

Unnamed: 42
True     2592
False       1
Name: count, dtype: int64

Unnamed: 43
True     2592
False       1
Name: count, dtype: int64

Unnamed: 44
True     2592
False       1
Name: count, dtype: int64

Unnamed: 45
True     2592
False       1
Name: count, dtype: int64

Unnamed: 46
True     2592
False       1
Name: count, dtype: int64

Unnamed: 47
True     2592
False       1
Name: count, dtype: int64

Unnamed: 48
True     2592
False       1
Name: count, dtype: int64

Unnamed: 49
True     2592
False       1
Name: count, dtype: int64

Unnamed: 50
True     2592
False       1
Name: count, dtype: int64

Unnamed: 51
True     2592
False       1
Name: count, dtype: int64

Unnamed: 52
True     2592
False       1
Name: count, dtype: int64

Unnamed: 53
True     2592
False       1
Name: count, dtype: int64

Unnamed: 54
True     2592
False       1
Name: count, dtype: int64

Unnamed: 55
True     2592
False       1
Name: count, dtype: int64

Unnamed: 56
True     2592
False       1
Name: count, dtype: int64

Unnamed: 57
True     2592
False       1
Name: count, dtype: int64

Unnamed: 58
True     2592
False       1
Name: count, dtype: int64

In [10]:
# Drop rows where both columns 'content' and 'summary' are empty
# #Check if the df is a dataframe
# if isinstance(df, pd.Series):
#     df = df.to_frame() # df is a series and not a dataframe. this converts it to a dataframe
# df_cleaned = df.dropna(axis=1, how= 'all')
# print("\nDataFrame After Dropping Columns with All NaN Values:\n", df_cleaned)
# # df.dropna() this drops NaN values from a series

In [11]:
# get the columns with NaN values and get their names
# cols_with_nan = df.columns[df.isnull().sum()]
cols_with_nan = df.columns[df.isnull().any()] #identify columns with all NaN values
# cols_with_nan_names = df.columns[cols_with_nan] #Get their names
print('\nColumns with NaN values', cols_with_nan.tolist())

Columns with NaN values ['title', 'url', 'summary', 'content', 'images', 'references', 'categories', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58']

In [12]:
df = df.drop(['Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 
              'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48',
              'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55',
              'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58'], axis = 1)

In [13]:
df.isnull()

      title    url  summary  content  images  references  categories
0     False  False    False     True   False       False       False
1     False  False    False     True   False       False       False
2     False  False    False    False   False       False       False
3     False  False    False     True   False       False       False
4     False  False    False    False   False       False       False
...     ...    ...      ...      ...     ...         ...         ...
2719  False  False    False    False   False       False       False
2720  False  False    False    False   False       False       False
2721  False  False    False    False   False       False       False
2723  False  False    False    False   False       False       False
2724  False  False    False    False   False       False       False

[2593 rows x 7 columns]

In [14]:
df.head()

,title,url,summary,content,images,references,categories
0,Ancient Greece,https://en.wikipedia.org/wiki/Ancient_Greece,Ancient GreeceAncient Greeká¼ÎÎÎÏromanizedHell...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,This roughly 15yearlong unification underPhili...,Ancient Greece
1,Ancient Greek,https://en.wikipedia.org/wiki/Ancient_Greek,Ancient Greeká¼ÎÎÎÎ½áÎºÎHellÄnikáhellÉËnikÉÌË1...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,Mycenaean Greekis imprecisely attested and som...,Ancient GreekAncient GreeceLanguages attested ...
2,Ancient Greek philosophy,https://en.wikipedia.org/wiki/Ancient_Greek_ph...,Ancient Greek philosophyarose in the 6th centu...,introductionAncient Greek philosophyarose in ...,https://upload.wikimedia.org/wikipedia/commons...,Alfred North Whitehead 1929Process and Reality...,Ancient Greek philosophyAncient philosophy by ...
3,Ancient Greek religion,https://en.wikipedia.org/wiki/Ancient_Greek_re...,Religious practices in ancient Greeceencompass...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,abBarbette Stanley Spaeth2013The Cambridge com...,Ancient Greek religion
4,Theatre of ancient Greece,https://en.wikipedia.org/wiki/Theatre_of_ancie...,Atheatricalculture flourished inancient Greece...,introductionAtheatricalculture flourished ina...,https://upload.wikimedia.org/wikipedia/en/thum...,MerriamWebster definition of tragedyArchivedfr...,Ancient Greek theatreAncient Greek dramatists ...

In [15]:
# # Transposing columns that have NaN values to rows and then dropping them
# # cols_with_nan = pd.DataFrame(df)
# transposed_df = df[cols_with_nan].transpose()
# print ('\n Transposed columns with NaN values:', {transposed_df})

In [16]:
print(df.columns)

Index(['title', 'url', 'summary', 'content', 'images', 'references',
       'categories'],
      dtype='object')

In [17]:

#this removes all the \n from the content table and summary
df["content"] = df["content"].str.replace("\n", " ", regex=True)
df["summary"] = df["summary"].str.replace("\n", " ", regex=True)
df["references"] = df["references"].str.replace("\n", " ", regex=True)
df["categories"] = df["categories"].str.replace("\n", " ", regex=True)

In [18]:

# def remove_url(text):
#     return re.sub(r'https?://\S+|www\.\S+', '', text)

# #This function removes punctuations
# def remove_punct(text):
#     return text.translate(str.maketrans('', '', string.punctuation))

# df['content'] = df['content'].apply(lambda x: remove_url(x))
# df['summary'] = df['summary'].apply(lambda x: remove_url(x))
# df['references'] = df['references'].apply(lambda x: remove_url(x))
# df['categories'] = df['categories'].apply(lambda x: remove_url(x))
# df['title'] = df['title'].apply(lambda x: remove_url(x))

In [19]:

# Remove special characters and single characters
df['content'] = df['content'].str.replace(r'[^A-Za-z0-9\s]', '', regex=True)  # Remove special characters
df['summary'] = df['summary'].str.replace(r'[^A-Za-z0-9\s]', '', regex=True)  # Remove special 
df['references'] = df['references'].str.replace(r'[^A-Za-z0-9\s]', '', regex=True)  # Remove special characters
df['categories'] = df['categories'].str.replace(r'[^A-Za-z0-9\s]', '', regex=True)  # Remove special characters


df['content'] = df['content'].str.replace(r'\b\w{1}\b', '', regex=True)
df['summary'] = df['summary'].str.replace(r'\b\w{1}\b', '', regex=True) 
df['refrences'] = df['references'].str.replace(r'[^A-Za-z0-9\s]', '', regex=True)  # Remove special characters
df['categories'] = df['categories'].str.replace(r'[^A-Za-z0-9\s]', '', regex=True)  # Remove special characters

# Display the updated DataFrame
print(df)

                                   title  \
0                         Ancient Greece
1                          Ancient Greek
2               Ancient Greek philosophy
3                 Ancient Greek religion
4              Theatre of ancient Greece
...                                  ...
2719                 Arcadocypriot Greek
2720                    Chthonic deities
2721  Religions of the ancient Near East
2723                            Choregos
2724                             Antheia

                                                    url  \
0          https://en.wikipedia.org/wiki/Ancient_Greece
1           https://en.wikipedia.org/wiki/Ancient_Greek
2     https://en.wikipedia.org/wiki/Ancient_Greek_ph...
3     https://en.wikipedia.org/wiki/Ancient_Greek_re...
4     https://en.wikipedia.org/wiki/Theatre_of_ancie...
...                                                 ...
2719  https://en.wikipedia.org/wiki/Arcadocypriot_Greek
2720     https://en.wikipedia.org/wiki/Chthonic_deities
2721  https://en.wikipedia.org/wiki/Religions_of_the...
2723             https://en.wikipedia.org/wiki/Choregos
2724              https://en.wikipedia.org/wiki/Antheia

                                                summary  \
0     Ancient GreeceAncient GreekromanizedHells was ...
1     Ancient GreekHellnikhellnik1includes the forms...
2     Ancient Greek philosophyarose in the 6th centu...
3     Religious practices in ancient Greeceencompass...
4     Atheatricalculture flourished inancient Greece...
...                                                 ...
2719  Arcadocypriot orsouthernAchaean was anancient ...
2720  InGreek mythology deities referred to aschthon...
2721  Thereligionsof theancient Near Eastwere mostly...
2723  In thetheatre of ancient Greece thechoregosplc...
2724  InAncient Greek religionAntheiaAncient Greekli...

                                                content  \
0                                                   NaN
1                                                   NaN
2      introductionAncient Greek philosophyarose in ...
3                                                   NaN
4      introductionAtheatricalculture flourished ina...
...                                                 ...
2719   introductionArcadocypriot orsouthernAchaean w...
2720   introductionInGreek mythology deities referre...
2721   introductionThereligionsof theancient Near Ea...
2723   introductionIn thetheatre of ancient Greece t...
2724   introductionInAncient Greek religionAntheiaAn...

                                                 images  \
0     https://upload.wikimedia.org/wikipedia/en/thum...
1     https://upload.wikimedia.org/wikipedia/en/thum...
2     https://upload.wikimedia.org/wikipedia/commons...
3     https://upload.wikimedia.org/wikipedia/en/thum...
4     https://upload.wikimedia.org/wikipedia/en/thum...
...                                                 ...
2719  https://upload.wikimedia.org/wikipedia/en/thum...
2720  https://upload.wikimedia.org/wikipedia/commons...
2721  https://upload.wikimedia.org/wikipedia/en/thum...
2723  https://upload.wikimedia.org/wikipedia/commons...
2724  https://en.wikipedia.org/static/images/footer/...

                                             references  \
0     This roughly 15yearlong unification underPhili...
1     Mycenaean Greekis imprecisely attested and som...
2     Alfred North Whitehead 1929Process and Reality...
3     abBarbette Stanley Spaeth2013The Cambridge com...
4     MerriamWebster definition of tragedyArchivedfr...
...                                                 ...
2719  Roger D Woodard 2008 Greek dialects inThe Anci...
2720  Also referred to as thechthonian gods1or theGr...
2721  Samuel H Hooke 1970The Siege Perilous Essays i...
2723  The Attic and Doric form was  choragos rather ...
2724  Willetsp 209PirenneDelforge and Pirontisv Hera...

                                             categories  \
0                                        Ancient Greece
1     Ancient GreekAncient GreeceLanguages attested ...
2     Ancient Greek philosophyAncient philosophy by ...
3                                Ancient Greek religion
4     Ancient Greek theatreAncient Greek dramatists ...
...                                                 ...
2719  Arcadocypriot GreekVarieties of Ancient GreekL...
2720  Chthonic beingsCulture of ancient GreeceGreek ...
2721  Ancient Near East religionAncient Semitic reli...
2723  Ancient Greek theatreAncient Athenian titlesTa...
2724              Epithets of AphroditeEpithets of Hera

                                              refrences
0     This roughly 15yearlong unification underPhili...
1     Mycenaean Greekis imprecisely attested and som...
2     Alfred North Whitehead 1929Process and Reality...
3     abBarbette Stanley Spaeth2013The Cambridge com...
4     MerriamWebster definition of tragedyArchivedfr...
...                                                 ...
2719  Roger D Woodard 2008 Greek dialects inThe Anci...
2720  Also referred to as thechthonian gods1or theGr...
2721  Samuel H Hooke 1970The Siege Perilous Essays i...
2723  The Attic and Doric form was  choragos rather ...
2724  Willetsp 209PirenneDelforge and Pirontisv Hera...

[2593 rows x 8 columns]

In [20]:
# Remove columns with all NaN values only
# df=df.dropna(axis=1, thresh = 1)

In [21]:
# Remove columns with atleast one NaN
# df=df.dropna()

In [22]:
df.head()

,title,url,summary,content,images,references,categories,refrences
0,Ancient Greece,https://en.wikipedia.org/wiki/Ancient_Greece,Ancient GreeceAncient GreekromanizedHells was ...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,This roughly 15yearlong unification underPhili...,Ancient Greece,This roughly 15yearlong unification underPhili...
1,Ancient Greek,https://en.wikipedia.org/wiki/Ancient_Greek,Ancient GreekHellnikhellnik1includes the forms...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,Mycenaean Greekis imprecisely attested and som...,Ancient GreekAncient GreeceLanguages attested ...,Mycenaean Greekis imprecisely attested and som...
2,Ancient Greek philosophy,https://en.wikipedia.org/wiki/Ancient_Greek_ph...,Ancient Greek philosophyarose in the 6th centu...,introductionAncient Greek philosophyarose in ...,https://upload.wikimedia.org/wikipedia/commons...,Alfred North Whitehead 1929Process and Reality...,Ancient Greek philosophyAncient philosophy by ...,Alfred North Whitehead 1929Process and Reality...
3,Ancient Greek religion,https://en.wikipedia.org/wiki/Ancient_Greek_re...,Religious practices in ancient Greeceencompass...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,abBarbette Stanley Spaeth2013The Cambridge com...,Ancient Greek religion,abBarbette Stanley Spaeth2013The Cambridge com...
4,Theatre of ancient Greece,https://en.wikipedia.org/wiki/Theatre_of_ancie...,Atheatricalculture flourished inancient Greece...,introductionAtheatricalculture flourished ina...,https://upload.wikimedia.org/wikipedia/en/thum...,MerriamWebster definition of tragedyArchivedfr...,Ancient Greek theatreAncient Greek dramatists ...,MerriamWebster definition of tragedyArchivedfr...

In [23]:


def getDuplicateColumns(df):
    # Find duplicate columns that have identical data.
    duplicateColumnNames = set()

    for x in range(df.shape[1]):
        col = df.iloc[:, x]

        for y in range(x + 1, df.shape[1]):
            otherCol = df.iloc[:, y]

            # If columns have identical values, mark as duplicate
            if col.equals(otherCol):
                duplicateColumnNames.add(df.columns[y])

    return list(duplicateColumnNames)

# Load dataset
# df = greece.load_dataset(file_path)
if __name__ == "__main__":
    # Get the list of duplicate columns
    duplicateColNames = getDuplicateColumns(df)

In [24]:
 if duplicateColNames:
        print("Duplicate Columns:", duplicateColNames)

        # Remove the duplicate columns
        df = df.drop(columns=duplicateColNames)
        print("\nDataFrame after removing duplicates:\n", df.head())
else:
    print("No duplicate columns found!")

Duplicate Columns: ['refrences']

DataFrame after removing duplicates:
                        title  \
0             Ancient Greece
1              Ancient Greek
2   Ancient Greek philosophy
3     Ancient Greek religion
4  Theatre of ancient Greece

                                                 url  \
0       https://en.wikipedia.org/wiki/Ancient_Greece
1        https://en.wikipedia.org/wiki/Ancient_Greek
2  https://en.wikipedia.org/wiki/Ancient_Greek_ph...
3  https://en.wikipedia.org/wiki/Ancient_Greek_re...
4  https://en.wikipedia.org/wiki/Theatre_of_ancie...

                                             summary  \
0  Ancient GreeceAncient GreekromanizedHells was ...
1  Ancient GreekHellnikhellnik1includes the forms...
2  Ancient Greek philosophyarose in the 6th centu...
3  Religious practices in ancient Greeceencompass...
4  Atheatricalculture flourished inancient Greece...

                                             content  \
0                                                NaN
1                                                NaN
2   introductionAncient Greek philosophyarose in ...
3                                                NaN
4   introductionAtheatricalculture flourished ina...

                                              images  \
0  https://upload.wikimedia.org/wikipedia/en/thum...
1  https://upload.wikimedia.org/wikipedia/en/thum...
2  https://upload.wikimedia.org/wikipedia/commons...
3  https://upload.wikimedia.org/wikipedia/en/thum...
4  https://upload.wikimedia.org/wikipedia/en/thum...

                                          references  \
0  This roughly 15yearlong unification underPhili...
1  Mycenaean Greekis imprecisely attested and som...
2  Alfred North Whitehead 1929Process and Reality...
3  abBarbette Stanley Spaeth2013The Cambridge com...
4  MerriamWebster definition of tragedyArchivedfr...

                                          categories
0                                     Ancient Greece
1  Ancient GreekAncient GreeceLanguages attested ...
2  Ancient Greek philosophyAncient philosophy by ...
3                             Ancient Greek religion
4  Ancient Greek theatreAncient Greek dramatists ...

In [25]:
df.head()

,title,url,summary,content,images,references,categories
0,Ancient Greece,https://en.wikipedia.org/wiki/Ancient_Greece,Ancient GreeceAncient GreekromanizedHells was ...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,This roughly 15yearlong unification underPhili...,Ancient Greece
1,Ancient Greek,https://en.wikipedia.org/wiki/Ancient_Greek,Ancient GreekHellnikhellnik1includes the forms...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,Mycenaean Greekis imprecisely attested and som...,Ancient GreekAncient GreeceLanguages attested ...
2,Ancient Greek philosophy,https://en.wikipedia.org/wiki/Ancient_Greek_ph...,Ancient Greek philosophyarose in the 6th centu...,introductionAncient Greek philosophyarose in ...,https://upload.wikimedia.org/wikipedia/commons...,Alfred North Whitehead 1929Process and Reality...,Ancient Greek philosophyAncient philosophy by ...
3,Ancient Greek religion,https://en.wikipedia.org/wiki/Ancient_Greek_re...,Religious practices in ancient Greeceencompass...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,abBarbette Stanley Spaeth2013The Cambridge com...,Ancient Greek religion
4,Theatre of ancient Greece,https://en.wikipedia.org/wiki/Theatre_of_ancie...,Atheatricalculture flourished inancient Greece...,introductionAtheatricalculture flourished ina...,https://upload.wikimedia.org/wikipedia/en/thum...,MerriamWebster definition of tragedyArchivedfr...,Ancient Greek theatreAncient Greek dramatists ...

In [26]:
# df = df.dropna(subset=[3], axis=1)

In [27]:
df.head()

,title,url,summary,content,images,references,categories
0,Ancient Greece,https://en.wikipedia.org/wiki/Ancient_Greece,Ancient GreeceAncient GreekromanizedHells was ...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,This roughly 15yearlong unification underPhili...,Ancient Greece
1,Ancient Greek,https://en.wikipedia.org/wiki/Ancient_Greek,Ancient GreekHellnikhellnik1includes the forms...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,Mycenaean Greekis imprecisely attested and som...,Ancient GreekAncient GreeceLanguages attested ...
2,Ancient Greek philosophy,https://en.wikipedia.org/wiki/Ancient_Greek_ph...,Ancient Greek philosophyarose in the 6th centu...,introductionAncient Greek philosophyarose in ...,https://upload.wikimedia.org/wikipedia/commons...,Alfred North Whitehead 1929Process and Reality...,Ancient Greek philosophyAncient philosophy by ...
3,Ancient Greek religion,https://en.wikipedia.org/wiki/Ancient_Greek_re...,Religious practices in ancient Greeceencompass...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,abBarbette Stanley Spaeth2013The Cambridge com...,Ancient Greek religion
4,Theatre of ancient Greece,https://en.wikipedia.org/wiki/Theatre_of_ancie...,Atheatricalculture flourished inancient Greece...,introductionAtheatricalculture flourished ina...,https://upload.wikimedia.org/wikipedia/en/thum...,MerriamWebster definition of tragedyArchivedfr...,Ancient Greek theatreAncient Greek dramatists ...

In [28]:
# removing links from the summary and content columns
#remove urls
import string

def remove_url(text):
    if isinstance(text, str):
        return re.sub(r'https?://\S+|www\.\S+', '', text)
    return text

#This function removes punctuations
def remove_punct(text):
    if isinstance (text, str):
        return text.translate(str.maketrans('', '', string.punctuation))
    return text

columns = ['summary', 'categories', 'references', 'title']

for col in columns:
    df[col] = df[col].astype(str).apply(lambda x: remove_punct(remove_url(x)))

# df['summary'] = df['summary'].apply(lambda x: remove_url(x))
# df['categories'] = df['categories'].apply(lambda x: remove_url(x))
# df['references'] = df['references'].apply(lambda x: remove_url(x))
# df['title'] = df['title'].apply(lambda x: remove_url(x))

In [29]:
df['references'].value_counts()

references
nan                                                                                                                                1858
 1990                                                                                                                                 2
 p 159                                                                                                                                2
 and finally                                                                                                                          2
 1999                                                                                                                                 2
                                                                                                                                   ...
 about to become ahuman sacrifice                                                                                                     1
 p 285                                                                                                                                1
 Why Is Sappho a Man                                                                                                                  1
 vol 1                                                                                                                                1
Willetsp 209PirenneDelforge and Pirontisv Hera Smithsv AntheiaLSJsv Pausanias2221Willetsp 209 Smithsv AntheiaLSJsv Hesychiussv        1
Name: count, Length: 729, dtype: int64

In [30]:
import wordninja
import pandas as pd

text_cols = ['references', 'categories', 'summary', ]
df[text_cols] = df[text_cols].fillna("").astype(str).applymap(lambda x: " ".join(wordninja.split(x)))

C:\Users\kiman\AppData\Local\Temp\ipykernel_11620\2390049610.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[text_cols] = df[text_cols].fillna("").astype(str).applymap(lambda x: " ".join(wordninja.split(x)))

In [31]:
# Normalize the Dataframe
# convert the text to lower case
text_cols = ['title','categories', 'references','images','url']
for col in text_cols:
    df[col] = df[col].astype(str).str.lower()

In [32]:
import re
from calendar import month_name

# Create a dictionary mapping month names to numbers
month_to_num = {name.lower(): f"{i:02}" for i, name in enumerate(month_name) if i}

# Patterns for date formats
full_date_pattern = re.compile(
    r'\b(' + '|'.join(month_to_num.keys()) + r')\s+(\d{1,2})\s+(\d{4})\b', flags=re.IGNORECASE
)
month_year_pattern = re.compile(
    r'\b(' + '|'.join(month_to_num.keys()) + r')\s+(\d{4})\b', flags=re.IGNORECASE
)

# Sample text
sample_text = "The shuttle mission was completed on March 9 2011 and another mission happened in July 2011."

# Find matches
full_matches = full_date_pattern.findall(sample_text)
month_year_matches = month_year_pattern.findall(sample_text)

print("Full Date Matches:", full_matches)
print("Month-Year Matches:", month_year_matches)

Full Date Matches: [('March', '9', '2011')]
Month-Year Matches: [('July', '2011')]

In [33]:
# Regex for YYYYMMDD dates
yyyymmdd_pattern = re.compile(r'\b(20\d{6})\b')

def standardize_full_date(match):
    """Convert 'March 9 2011' to '2011-03-09'."""
    month_str, day, year = match.groups()
    month_num = month_to_num.get(month_str.lower(), "00")  # Default to '00' if not found
    day_formatted = f"{int(day):02}"  # Ensure day is two digits
    return f"{year}-{month_num}-{day_formatted}"

def standardize_month_year(match):
    """Convert 'July 2011' to '2011-07'."""
    month_str, year = match.groups()
    month_num = month_to_num.get(month_str.lower(), "00")
    return f"{year}-{month_num}"


def standardize_yyyymmdd(match):
    """Convert 'YYYYMMDD' to 'YYYY-MM-DD'."""
    date_str = match.group(1)
    return f"{date_str[:4]}-{date_str[4:6]}-{date_str[6:]}"  # Format as YYYY-MM-DD

# Update process_dates function to include this new pattern
def process_dates(text):
    # Standardize full dates (e.g., "March 9 2011" -> "2011-03-09")
    text = full_date_pattern.sub(standardize_full_date, text)

    # Standardize month-year dates (e.g., "July 2011" -> "2011-07")
    text = month_year_pattern.sub(standardize_month_year, text)

    # Standardize YYYYMMDD format (e.g., "20220405" -> "2022-04-05")
    text = yyyymmdd_pattern.sub(standardize_yyyymmdd, text)

    return text

In [34]:
df['categories'] = df['categories'].astype(str).apply(process_dates)
df['references'] = df['references'].astype(str).apply(process_dates)
df['summary'] = df['summary'].astype(str).apply(process_dates)

In [35]:
df['summary'].value_counts()

summary
nan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1287
2006                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 6
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     5
1992                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 3

In [40]:
df.head(10)

,title,url,summary,content,images,references,categories
0,ancient greece,https://en.wikipedia.org/wiki/ancient_greece,Ancient Greece Ancient Greek romanized Hells w...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,this roughly 15 year long unification under ph...,ancient greece
1,ancient greek,https://en.wikipedia.org/wiki/ancient_greek,Ancient Greek Hell nik hell nik 1 includes the...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,mycenaean greek is imprecisely attested and so...,ancient greek ancient greece languages atteste...
2,ancient greek philosophy,https://en.wikipedia.org/wiki/ancient_greek_ph...,Ancient Greek philosophy arose in the 6 th cen...,introductionAncient Greek philosophyarose in ...,https://upload.wikimedia.org/wikipedia/commons...,alfred north whitehead 1929 process and realit...,ancient greek philosophy ancient philosophy by...
3,ancient greek religion,https://en.wikipedia.org/wiki/ancient_greek_re...,Religious practices in ancient Greece encompas...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,abba r bette stanley spa eth 2013 the cambridg...,ancient greek religion
4,theatre of ancient greece,https://en.wikipedia.org/wiki/theatre_of_ancie...,A theatrical culture flourished in ancient Gre...,introductionAtheatricalculture flourished ina...,https://upload.wikimedia.org/wikipedia/en/thum...,merriam webster definition of tragedy archived...,ancient greek theatre ancient greek dramatists...
5,pederasty in ancient greece,https://en.wikipedia.org/wiki/pederasty_in_anc...,Pederasty in ancient Greece was socially ackno...,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,the seven functions that a free athenian citiz...,pederasty in ancient greece philosophy of love...
6,list of ancient greek philosophers,https://en.wikipedia.org/wiki/list_of_ancient_...,This list of ancient Greek philosophers contai...,introductionThislist of ancient Greek philoso...,https://upload.wikimedia.org/wikipedia/en/thum...,aristotle metaphysics alpha 983 b 18 russell b...,ancient greek philosophers ancient greek philo...
7,ancient greek art,https://en.wikipedia.org/wiki/ancient_greek_art,Ancient Greek art stands out among that of oth...,introductionAncient Greek artstands out among...,https://upload.wikimedia.org/wikipedia/commons...,boardman 34 cook 12 cook 12 cook 1418 athena w...,ancient greek art greek art arts in greece
8,ancient greek cuisine,https://en.wikipedia.org/wiki/ancient_greek_cu...,Ancient Greek cuisine was characterized by its...,introductionAncient Greek cuisinewas characte...,https://upload.wikimedia.org/wikipedia/en/thum...,ab lacus curt ius athena eus de ip no sophist ...,ancient greek cuisine cuisine by culture greek...
9,homosexuality in ancient greece,https://en.wikipedia.org/wiki/homosexuality_in...,In classical antiquity writers such as Herodot...,introductionInclassical antiquity writers suc...,https://upload.wikimedia.org/wikipedia/en/thum...,ab jared alan johnson 2015 the greek you the n...,sexuality in ancient greece lgbt q history in ...

In [37]:
nltk.download('wordnet') #Download wordnet
# lemmatizzer initialization
lemmatizer = WordNetLemmatizer()
 # Function to lemmatizer
def lemmatize(text):
    if isinstance(text, str): #Ensure it is a string
        return ''.join([lemmatizer.lemmatizer(word) for word in text.split()])
    return text # return as is not a string

    # apply lemmatization
lemmatize_col = ['title', 'summary', 'references', 'categories']
df[lemmatize_col] = df[lemmatize_col].apply(lemmatize)
print (df)

                                   title  \
0                         ancient greece
1                          ancient greek
2               ancient greek philosophy
3                 ancient greek religion
4              theatre of ancient greece
...                                  ...
2719                 arcadocypriot greek
2720                    chthonic deities
2721  religions of the ancient near east
2723                            choregos
2724                             antheia

                                                    url  \
0          https://en.wikipedia.org/wiki/ancient_greece
1           https://en.wikipedia.org/wiki/ancient_greek
2     https://en.wikipedia.org/wiki/ancient_greek_ph...
3     https://en.wikipedia.org/wiki/ancient_greek_re...
4     https://en.wikipedia.org/wiki/theatre_of_ancie...
...                                                 ...
2719  https://en.wikipedia.org/wiki/arcadocypriot_greek
2720     https://en.wikipedia.org/wiki/chthonic_deities
2721  https://en.wikipedia.org/wiki/religions_of_the...
2723             https://en.wikipedia.org/wiki/choregos
2724              https://en.wikipedia.org/wiki/antheia

                                                summary  \
0     Ancient Greece Ancient Greek romanized Hells w...
1     Ancient Greek Hell nik hell nik 1 includes the...
2     Ancient Greek philosophy arose in the 6 th cen...
3     Religious practices in ancient Greece encompas...
4     A theatrical culture flourished in ancient Gre...
...                                                 ...
2719  Arca do cypriot or southern Achaean was an anc...
2720  In Greek mythology deities referred to a sch t...
2721  The religions of the ancient Near East were mo...
2723  In the theatre of ancient Greece the chore go ...
2724  In Ancient Greek religion An theia Ancient Gre...

                                                content  \
0                                                   NaN
1                                                   NaN
2      introductionAncient Greek philosophyarose in ...
3                                                   NaN
4      introductionAtheatricalculture flourished ina...
...                                                 ...
2719   introductionArcadocypriot orsouthernAchaean w...
2720   introductionInGreek mythology deities referre...
2721   introductionThereligionsof theancient Near Ea...
2723   introductionIn thetheatre of ancient Greece t...
2724   introductionInAncient Greek religionAntheiaAn...

                                                 images  \
0     https://upload.wikimedia.org/wikipedia/en/thum...
1     https://upload.wikimedia.org/wikipedia/en/thum...
2     https://upload.wikimedia.org/wikipedia/commons...
3     https://upload.wikimedia.org/wikipedia/en/thum...
4     https://upload.wikimedia.org/wikipedia/en/thum...
...                                                 ...
2719  https://upload.wikimedia.org/wikipedia/en/thum...
2720  https://upload.wikimedia.org/wikipedia/commons...
2721  https://upload.wikimedia.org/wikipedia/en/thum...
2723  https://upload.wikimedia.org/wikipedia/commons...
2724  https://en.wikipedia.org/static/images/footer/...

                                             references  \
0     this roughly 15 year long unification under ph...
1     mycenaean greek is imprecisely attested and so...
2     alfred north whitehead 1929 process and realit...
3     abba r bette stanley spa eth 2013 the cambridg...
4     merriam webster definition of tragedy archived...
...                                                 ...
2719  roger d wood ard 2008 greek dialects in the an...
2720  also referred to as the ch th on ian gods 1 or...
2721  samuel h hooke 1970 the siege perilous essays ...
2723  the attic and doric form was chor agos rather ...
2724  wille tsp 209 pir enne del forge and pir on ti...

                                             categories
0                                        ancient greece
1     ancient greek ancient greece languages atteste...
2     ancient greek philosophy ancient philosophy by...
3                                ancient greek religion
4     ancient greek theatre ancient greek dramatists...
...                                                 ...
2719  arca do cypriot greek varieties of ancient gre...
2720  ch th onic beings culture of ancient greece gr...
2721  ancient near east religion ancient semitic rel...
2723  ancient greek theatre ancient athenian titles ...
2724            epithets of aphrodite epithets of her a

[2593 rows x 7 columns]

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\kiman\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [38]:
# initializer stemmer
stemmer = PorterStemmer()

# function to stem word
def stem_word(text):
    if isinstance(text, str):
        return ''.join([stemmer.stem(word)for word in text.split()])
    return text 

stem_col = ['title', 'summary', 'references', 'categories']
df[stem_col] = df[stem_col].apply(stem_word)
print (df)

                                   title  \
0                         ancient greece
1                          ancient greek
2               ancient greek philosophy
3                 ancient greek religion
4              theatre of ancient greece
...                                  ...
2719                 arcadocypriot greek
2720                    chthonic deities
2721  religions of the ancient near east
2723                            choregos
2724                             antheia

                                                    url  \
0          https://en.wikipedia.org/wiki/ancient_greece
1           https://en.wikipedia.org/wiki/ancient_greek
2     https://en.wikipedia.org/wiki/ancient_greek_ph...
3     https://en.wikipedia.org/wiki/ancient_greek_re...
4     https://en.wikipedia.org/wiki/theatre_of_ancie...
...                                                 ...
2719  https://en.wikipedia.org/wiki/arcadocypriot_greek
2720     https://en.wikipedia.org/wiki/chthonic_deities
2721  https://en.wikipedia.org/wiki/religions_of_the...
2723             https://en.wikipedia.org/wiki/choregos
2724              https://en.wikipedia.org/wiki/antheia

                                                summary  \
0     Ancient Greece Ancient Greek romanized Hells w...
1     Ancient Greek Hell nik hell nik 1 includes the...
2     Ancient Greek philosophy arose in the 6 th cen...
3     Religious practices in ancient Greece encompas...
4     A theatrical culture flourished in ancient Gre...
...                                                 ...
2719  Arca do cypriot or southern Achaean was an anc...
2720  In Greek mythology deities referred to a sch t...
2721  The religions of the ancient Near East were mo...
2723  In the theatre of ancient Greece the chore go ...
2724  In Ancient Greek religion An theia Ancient Gre...

                                                content  \
0                                                   NaN
1                                                   NaN
2      introductionAncient Greek philosophyarose in ...
3                                                   NaN
4      introductionAtheatricalculture flourished ina...
...                                                 ...
2719   introductionArcadocypriot orsouthernAchaean w...
2720   introductionInGreek mythology deities referre...
2721   introductionThereligionsof theancient Near Ea...
2723   introductionIn thetheatre of ancient Greece t...
2724   introductionInAncient Greek religionAntheiaAn...

                                                 images  \
0     https://upload.wikimedia.org/wikipedia/en/thum...
1     https://upload.wikimedia.org/wikipedia/en/thum...
2     https://upload.wikimedia.org/wikipedia/commons...
3     https://upload.wikimedia.org/wikipedia/en/thum...
4     https://upload.wikimedia.org/wikipedia/en/thum...
...                                                 ...
2719  https://upload.wikimedia.org/wikipedia/en/thum...
2720  https://upload.wikimedia.org/wikipedia/commons...
2721  https://upload.wikimedia.org/wikipedia/en/thum...
2723  https://upload.wikimedia.org/wikipedia/commons...
2724  https://en.wikipedia.org/static/images/footer/...

                                             references  \
0     this roughly 15 year long unification under ph...
1     mycenaean greek is imprecisely attested and so...
2     alfred north whitehead 1929 process and realit...
3     abba r bette stanley spa eth 2013 the cambridg...
4     merriam webster definition of tragedy archived...
...                                                 ...
2719  roger d wood ard 2008 greek dialects in the an...
2720  also referred to as the ch th on ian gods 1 or...
2721  samuel h hooke 1970 the siege perilous essays ...
2723  the attic and doric form was chor agos rather ...
2724  wille tsp 209 pir enne del forge and pir on ti...

                                             categories
0                                        ancient greece
1     ancient greek ancient greece languages atteste...
2     ancient greek philosophy ancient philosophy by...
3                                ancient greek religion
4     ancient greek theatre ancient greek dramatists...
...                                                 ...
2719  arca do cypriot greek varieties of ancient gre...
2720  ch th onic beings culture of ancient greece gr...
2721  ancient near east religion ancient semitic rel...
2723  ancient greek theatre ancient athenian titles ...
2724            epithets of aphrodite epithets of her a

[2593 rows x 7 columns]

In [41]:
# Url validation using regex
import re
regex = re.compile(
        r'^(?:http|ftp)s?://' # http:// or https://
        r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?)|' #domain...
        r'localhost|' #localhost...
        r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})' # ...or ip
        r'(?::\d+)?' # optional port
        r'(?:/?|[/?]\S+)$', re.IGNORECASE)

print(re.match(regex, "http://www.example.com") is not None) # True
print(re.match(regex, "example.com") is not None)            # False

True
False

In [45]:
# Url validation using the regex function
# Email validation using regex
import re
regex = re.compile(
        r'^(?:http|ftp)s?://' # http:// or https://
        r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?)|' #domain...
        r'localhost|' #localhost...
        r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})' # ...or ip
        r'(?::\d+)?' # optional port
        r'(?:/?|[/?]\S+)$', re.IGNORECASE
)
#  Function to check if url is valid
def is_url_valid (url):
    return re.match(regex, url) is not None
# Applty the URL validation function

df = df[df['url'].apply(is_url_valid)]

print(df)

                                   title  \
0                         ancient greece
1                          ancient greek
2               ancient greek philosophy
3                 ancient greek religion
4              theatre of ancient greece
...                                  ...
2719                 arcadocypriot greek
2720                    chthonic deities
2721  religions of the ancient near east
2723                            choregos
2724                             antheia

                                                    url  \
0          https://en.wikipedia.org/wiki/ancient_greece
1           https://en.wikipedia.org/wiki/ancient_greek
2     https://en.wikipedia.org/wiki/ancient_greek_ph...
3     https://en.wikipedia.org/wiki/ancient_greek_re...
4     https://en.wikipedia.org/wiki/theatre_of_ancie...
...                                                 ...
2719  https://en.wikipedia.org/wiki/arcadocypriot_greek
2720     https://en.wikipedia.org/wiki/chthonic_deities
2721  https://en.wikipedia.org/wiki/religions_of_the...
2723             https://en.wikipedia.org/wiki/choregos
2724              https://en.wikipedia.org/wiki/antheia

                                                summary  \
0     Ancient Greece Ancient Greek romanized Hells w...
1     Ancient Greek Hell nik hell nik 1 includes the...
2     Ancient Greek philosophy arose in the 6 th cen...
3     Religious practices in ancient Greece encompas...
4     A theatrical culture flourished in ancient Gre...
...                                                 ...
2719  Arca do cypriot or southern Achaean was an anc...
2720  In Greek mythology deities referred to a sch t...
2721  The religions of the ancient Near East were mo...
2723  In the theatre of ancient Greece the chore go ...
2724  In Ancient Greek religion An theia Ancient Gre...

                                                content  \
0                                                   NaN
1                                                   NaN
2      introductionAncient Greek philosophyarose in ...
3                                                   NaN
4      introductionAtheatricalculture flourished ina...
...                                                 ...
2719   introductionArcadocypriot orsouthernAchaean w...
2720   introductionInGreek mythology deities referre...
2721   introductionThereligionsof theancient Near Ea...
2723   introductionIn thetheatre of ancient Greece t...
2724   introductionInAncient Greek religionAntheiaAn...

                                                 images  \
0     https://upload.wikimedia.org/wikipedia/en/thum...
1     https://upload.wikimedia.org/wikipedia/en/thum...
2     https://upload.wikimedia.org/wikipedia/commons...
3     https://upload.wikimedia.org/wikipedia/en/thum...
4     https://upload.wikimedia.org/wikipedia/en/thum...
...                                                 ...
2719  https://upload.wikimedia.org/wikipedia/en/thum...
2720  https://upload.wikimedia.org/wikipedia/commons...
2721  https://upload.wikimedia.org/wikipedia/en/thum...
2723  https://upload.wikimedia.org/wikipedia/commons...
2724  https://en.wikipedia.org/static/images/footer/...

                                             references  \
0     this roughly 15 year long unification under ph...
1     mycenaean greek is imprecisely attested and so...
2     alfred north whitehead 1929 process and realit...
3     abba r bette stanley spa eth 2013 the cambridg...
4     merriam webster definition of tragedy archived...
...                                                 ...
2719  roger d wood ard 2008 greek dialects in the an...
2720  also referred to as the ch th on ian gods 1 or...
2721  samuel h hooke 1970 the siege perilous essays ...
2723  the attic and doric form was chor agos rather ...
2724  wille tsp 209 pir enne del forge and pir on ti...

                                             categories
0                                        ancient greece
1     ancient greek ancient greece languages atteste...
2     ancient greek philosophy ancient philosophy by...
3                                ancient greek religion
4     ancient greek theatre ancient greek dramatists...
...                                                 ...
2719  arca do cypriot greek varieties of ancient gre...
2720  ch th onic beings culture of ancient greece gr...
2721  ancient near east religion ancient semitic rel...
2723  ancient greek theatre ancient athenian titles ...
2724            epithets of aphrodite epithets of her a

[468 rows x 7 columns]

In [50]:
df.to_csv('cleaned_wikipedia_data_Ancient Greece(in).csv', index = False)