In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pl

In [55]:
df = pd.read_csv('ebay_laptop.csv')
df.head()

,Title,Subtitle,Price,Shipping,Location,Watch Count,Seller Info,Link,Image URL
0,"HP ProBook X360 11 G5 2-in-1 Laptop 11.6"" Wind...",Excellent - Refurbished · HP,$148.53,+$74.99 delivery,from United States,NaN,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/254582474636,https://i.ebayimg.com/images/g/F-8AAOSwcuRnf2T...
1,"Dell Latitude 13.3"" Laptop PC Computer Celeron...",Very Good - Refurbished · Dell · 500 GB,$109.45,+$82.22 delivery,from United States,NaN,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/284813504070,https://i.ebayimg.com/images/g/Y0EAAOSwKChnoW7...
2,"Dell Latitude 5400 14"" HD Laptop PC Core i7 4....",Excellent - Refurbished · Dell,$277.25,+$78.79 delivery,from United States,NaN,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/256496543516,https://i.ebayimg.com/images/g/5K8AAOSwQttnlEW...
3,"Dell Latitude Touchscreen 13.3"" FHD Core i7 La...",Excellent - Refurbished · Dell,$292.11,+$96.01 delivery,from United States,NaN,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/283987164379,https://i.ebayimg.com/images/g/A3MAAOSwteZnptZ...
4,"HP X360 11 G5 Laptop 11"" Touchscreen Pentium S...",Very Good - Refurbished · HP,$138.98,+$74.71 delivery,from United States,NaN,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/254654754368,https://i.ebayimg.com/images/g/Ky4AAOSwGEJngJi...

In [ ]:
#check for dupicatecs
df.duplicated().sum()

np.int64(357)

In [57]:
df = df.drop_duplicates()

In [58]:
missing_values = df.isnull()
missing_values.head()

,Title,Subtitle,Price,Shipping,Location,Watch Count,Seller Info,Link,Image URL
0,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,True,False,False,False

In [59]:

#list of columns with missing values
for column in missing_values.columns.values.tolist():
    print(column)
    print (missing_values[column].value_counts())
    print("")

Title
Title
False    10395
Name: count, dtype: int64

Subtitle
Subtitle
False    10395
Name: count, dtype: int64

Price
Price
False    10395
Name: count, dtype: int64

Shipping
Shipping
False    10395
Name: count, dtype: int64

Location
Location
False    10395
Name: count, dtype: int64

Watch Count
Watch Count
True     9608
False     787
Name: count, dtype: int64

Seller Info
Seller Info
False    10395
Name: count, dtype: int64

Link
Link
False    10395
Name: count, dtype: int64

Image URL
Image URL
False    10395
Name: count, dtype: int64

In [60]:
#droup colume watch count
df = df.drop(columns=['Watch Count'])

In [61]:
#standardize all the columns to low case
df.columns = df.columns.str.lower()

df.head()

,title,subtitle,price,shipping,location,seller info,link,image url
0,"HP ProBook X360 11 G5 2-in-1 Laptop 11.6"" Wind...",Excellent - Refurbished · HP,$148.53,+$74.99 delivery,from United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/254582474636,https://i.ebayimg.com/images/g/F-8AAOSwcuRnf2T...
1,"Dell Latitude 13.3"" Laptop PC Computer Celeron...",Very Good - Refurbished · Dell · 500 GB,$109.45,+$82.22 delivery,from United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/284813504070,https://i.ebayimg.com/images/g/Y0EAAOSwKChnoW7...
2,"Dell Latitude 5400 14"" HD Laptop PC Core i7 4....",Excellent - Refurbished · Dell,$277.25,+$78.79 delivery,from United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/256496543516,https://i.ebayimg.com/images/g/5K8AAOSwQttnlEW...
3,"Dell Latitude Touchscreen 13.3"" FHD Core i7 La...",Excellent - Refurbished · Dell,$292.11,+$96.01 delivery,from United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/283987164379,https://i.ebayimg.com/images/g/A3MAAOSwteZnptZ...
4,"HP X360 11 G5 Laptop 11"" Touchscreen Pentium S...",Very Good - Refurbished · HP,$138.98,+$74.71 delivery,from United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/254654754368,https://i.ebayimg.com/images/g/Ky4AAOSwGEJngJi...

In [62]:
df['location'] = df['location'].str.replace('from ', '', regex=False)
df['shipping'] = df['shipping'].str.replace('delivery', ' ', regex=False)
df['shipping'] = df['shipping'].str.replace('+', ' ', regex=False)

df.head()

,title,subtitle,price,shipping,location,seller info,link,image url
0,"HP ProBook X360 11 G5 2-in-1 Laptop 11.6"" Wind...",Excellent - Refurbished · HP,$148.53,$74.99,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/254582474636,https://i.ebayimg.com/images/g/F-8AAOSwcuRnf2T...
1,"Dell Latitude 13.3"" Laptop PC Computer Celeron...",Very Good - Refurbished · Dell · 500 GB,$109.45,$82.22,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/284813504070,https://i.ebayimg.com/images/g/Y0EAAOSwKChnoW7...
2,"Dell Latitude 5400 14"" HD Laptop PC Core i7 4....",Excellent - Refurbished · Dell,$277.25,$78.79,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/256496543516,https://i.ebayimg.com/images/g/5K8AAOSwQttnlEW...
3,"Dell Latitude Touchscreen 13.3"" FHD Core i7 La...",Excellent - Refurbished · Dell,$292.11,$96.01,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/283987164379,https://i.ebayimg.com/images/g/A3MAAOSwteZnptZ...
4,"HP X360 11 G5 Laptop 11"" Touchscreen Pentium S...",Very Good - Refurbished · HP,$138.98,$74.71,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/254654754368,https://i.ebayimg.com/images/g/Ky4AAOSwGEJngJi...

In [63]:
#remove emojis

df=df.astype(str).apply(lambda x: x.str.encode('ascii', 'ignore').str.decode('ascii'))

In [64]:
#remove urls
def remove_url(text):
    return re.sub(r'https?://\S+|www\.\S+', '', text)

In [65]:
#This function removes punctuations
def remove_punct(text):
    return text.translate(str.maketrans('', '', string.punctuation))

In [66]:
df = df.reset_index(drop=True)
df.head()

,title,subtitle,price,shipping,location,seller info,link,image url
0,"HP ProBook X360 11 G5 2-in-1 Laptop 11.6"" Wind...",Excellent - Refurbished HP,$148.53,$74.99,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/254582474636,https://i.ebayimg.com/images/g/F-8AAOSwcuRnf2T...
1,"Dell Latitude 13.3"" Laptop PC Computer Celeron...",Very Good - Refurbished Dell 500 GB,$109.45,$82.22,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/284813504070,https://i.ebayimg.com/images/g/Y0EAAOSwKChnoW7...
2,"Dell Latitude 5400 14"" HD Laptop PC Core i7 4....",Excellent - Refurbished Dell,$277.25,$78.79,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/256496543516,https://i.ebayimg.com/images/g/5K8AAOSwQttnlEW...
3,"Dell Latitude Touchscreen 13.3"" FHD Core i7 La...",Excellent - Refurbished Dell,$292.11,$96.01,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/283987164379,https://i.ebayimg.com/images/g/A3MAAOSwteZnptZ...
4,"HP X360 11 G5 Laptop 11"" Touchscreen Pentium S...",Very Good - Refurbished HP,$138.98,$74.71,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/254654754368,https://i.ebayimg.com/images/g/Ky4AAOSwGEJngJi...

In [67]:
#remove dolar sign from columns size and price
df['shipping'] = df['shipping'].str.replace('$', '', regex=False)
df['price'] = df['price'].str.replace('$', '', regex=False)

In [ ]:
#remove ranga from columns size and price

df = df[~df['seller info'].str.contains('renga', case=False, na=False)]
df = df[~df['price'].str.contains('renga', case=False, na=False)]
df.head()

,title,subtitle,price,shipping,location,seller info,link,image url
0,"HP ProBook X360 11 G5 2-in-1 Laptop 11.6"" Wind...",Excellent - Refurbished HP,148.53,74.99,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/254582474636,https://i.ebayimg.com/images/g/F-8AAOSwcuRnf2T...
1,"Dell Latitude 13.3"" Laptop PC Computer Celeron...",Very Good - Refurbished Dell 500 GB,109.45,82.22,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/284813504070,https://i.ebayimg.com/images/g/Y0EAAOSwKChnoW7...
2,"Dell Latitude 5400 14"" HD Laptop PC Core i7 4....",Excellent - Refurbished Dell,277.25,78.79,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/256496543516,https://i.ebayimg.com/images/g/5K8AAOSwQttnlEW...
3,"Dell Latitude Touchscreen 13.3"" FHD Core i7 La...",Excellent - Refurbished Dell,292.11,96.01,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/283987164379,https://i.ebayimg.com/images/g/A3MAAOSwteZnptZ...
4,"HP X360 11 G5 Laptop 11"" Touchscreen Pentium S...",Very Good - Refurbished HP,138.98,74.71,United States,"discountcomputerdepot (126,963) 98.6%",https://www.ebay.com/itm/254654754368,https://i.ebayimg.com/images/g/Ky4AAOSwGEJngJi...

In [69]:
df = df[~df["price"].astype(str).str.contains("to")]

In [70]:
df.to_csv('ttttttttttdd.csv')

In [71]:
# search for a value in the price column with 2 decimal places
df["price"] = df["price"].astype(str).str.replace(r"(?<=\d)\.(?=.*\.)", "", regex=True)
df["shipping"] = df["shipping"].astype(str).str.replace(r"[^\d.]", "", regex=True)

In [72]:
# Function to clean the Price column
def price(price):
    price = str(price).replace(",", "")  # Remove commas
    if "to" in price:
        price = price.split("to")[0]  # Take the first value in a range
    try:
        return float(price)  # Convert to float
    except ValueError:
        return None  # Handle non-convertible values

# Apply cleaning function
df["price"] = df["price"].apply(price)

In [73]:
def price(price):
    if pd.isna(price) or price == "":  # Handle missing or empty values
        return None  # Or use 0 if you prefer
    price = str(price).replace(",", "").strip()  # Remove commas and trim spaces
    if "to" in price:
        price = price.split("to")[0]  # Take the first value in a range
    try:
        return float(price)  # Convert to float
    except ValueError:
        return None  # Handle any remaining invalid values

# Apply cleaning function
df["price"] = df["price"].apply(price)

In [75]:


# replace all empty strings with NaN
df.replace("", np.nan, inplace=True)

In [76]:
# # change dtype of price and shipping+deliveryfee columns to float
df["price"] = df["price"].astype(float)
df["shipping"] = df["shipping"].astype(float)

In [77]:
# total number of rows with nan values in the dataset
totaln = df.isnull().sum()

# total number of rows in the dataset
totalt = df.shape[0]
print(totalt / totaln)

title               inf
subtitle            inf
price               inf
shipping       7.473455
location            inf
seller info         inf
link                inf
image url           inf
dtype: float64

In [78]:
# replace nan values with mean in the shipping+deliveryfee column
df["shipping"].fillna(df["shipping"].mean(), inplace=True)

C:\Users\lish\AppData\Local\Temp\ipykernel_12988\448592507.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["shipping"].fillna(df["shipping"].mean(), inplace=True)

In [80]:
df = df.reset_index(drop=True)

In [81]:
df.to_csv('ebay_clean.csv')